### ISSUE TITLE
При генерации вики добавить переход строки, косле заголовка в примере выполнения

### ISSUE THREAD

**Issue by zildarius** [kreig133/IASKDaoGenerator#13]
При генерации вики для описания ХП/запроса имеется такая строчка начинающая пример:
                    h5. Пример выполнения: {code:language=sql}declare
Надо сделать перенос строки:
                    h5. Пример выполнения:
                    {code:language=sql}declare

**Comment by gbax** [comment]
это ты сам мог сделать в шаблоне xsl
