### ISSUE TITLE
драйвер для подключения к БД

### ISSUE THREAD

**Issue by AnonymousVovus** [kreig133/IASKDaoGenerator#23]
В версии dao-generator-а для депозитариев необходимо сменить драйвер подключения к БД. В генерируемом тестовом проекте также надо сменить драйвер.

Необходимо использовать вот этот драйвер
<dependency>
    <groupId>net.sourceforge.jtds</groupId>
    <artifactId>jtds</artifactId>
    <version>1.2.4</version>
</dependency>

настройки для этого драйвера следующие:
jdbc.driverClass=net.sourceforge.jtds.jdbc.Driver
jdbc.url=jdbc:jtds:sqlserver://aaa.bbb.ccc.ddd/dbname

**Comment by kreig133** [comment]
причина не понятна.
все используют старый и все норм.
