### ISSUE TITLE
Генерация тестового проекта

### ISSUE THREAD

**Issue by AnonymousVovus** [kreig133/IASKDaoGenerator#24]
Для того чтобы повторно сгенерировать тестовый проект приходится каждый раз удалять существующий проект. В противном случае dao-generator отказывается генерить что-либо вменяемое.

**Comment by kreig133** [comment]
1. Генерировать в другую папку.
2. Нажать кнопку Clear перед новой генерацией.

Автоматическую очистку делать не стоит.
