### ISSUE TITLE
application.properties

### ISSUE THREAD

**Issue by AnonymousVovus** [kreig133/IASKDaoGenerator#25]
В версии для депозитариев, при генерации тестового проекта используется application.properties из ресурсов, в котором указаны невалидные на текущий момент настройки. Причем если используется режим работы "для аналитика" то берется правильный application.properties, указанный извне.
Для тестового проекта application.properties тоже должен брать извне, а не из ресурсов.

**Comment by kreig133** [comment]
Я закрыл те таски, потому что Марат перенес их в JIRA.
Может этот тоже туда?
